In [2]:
import torch

In [3]:
x = torch.ones(5) #input tensor
y = torch.zeros(3) #expected output
w = torch.randn(5,3,requires_grad=True)
b = torch.randn(3,requires_grad=True)
z = torch.matmul(x,w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)


In [4]:
loss

tensor(0.2243, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [5]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x0000021CFB6269A0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x0000021CFB6FE7C0>


In [6]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.1206, 0.0105, 0.0581],
        [0.1206, 0.0105, 0.0581],
        [0.1206, 0.0105, 0.0581],
        [0.1206, 0.0105, 0.0581],
        [0.1206, 0.0105, 0.0581]])
tensor([0.1206, 0.0105, 0.0581])


In [7]:
z = torch.matmul(x,w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x,w)+b
print(z.requires_grad)

True
False


In [13]:
z = torch.matmul(x,w)+b
print(z.requires_grad)
z.detach_()
print(z.requires_grad)

True
False


In [17]:
inp = torch.eye(5,requires_grad=True)
out = (inp+1).pow(2)
print(inp)


tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], requires_grad=True)


In [18]:
print(out)

tensor([[4., 1., 1., 1., 1.],
        [1., 4., 1., 1., 1.],
        [1., 1., 4., 1., 1.],
        [1., 1., 1., 4., 1.],
        [1., 1., 1., 1., 4.]], grad_fn=<PowBackward0>)


In [19]:
out.backward(torch.ones_like(inp), retain_graph=True)
print("First call: ",inp.grad)
out.backward(torch.ones_like(inp), retain_graph=True)
print("Second call: ",inp.grad)
inp.grad.zero_()
out.backward(torch.ones_like(inp), retain_graph=True)
print("Call after zeroing gradients: ",inp.grad)

First call:  tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])
Second call:  tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.],
        [4., 4., 4., 4., 8.]])
Call after zeroing gradients:  tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])
