In [47]:
import torch

In [48]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [49]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])

In [50]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [51]:
points = torch.tensor([[4.0,1.0],[5.0,3.0], [2.0,1.0]])

In [52]:
points.shape

torch.Size([3, 2])

In [53]:
img_t = torch.randn(3,5,5) #Shape [channels, rows,columns]
weights = torch.tensor([0.2126,0.7152,0.0722])
weights

tensor([0.2126, 0.7152, 0.0722])

In [54]:
batch_t = torch.randn(2,3,5,5)

In [55]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [56]:
unqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t*unqueezed_weights)
batch_weights = (batch_t*unqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_gray_weighted.shape, img_gray_weighted.shape


(torch.Size([2, 5, 5]), torch.Size([5, 5]))

In [57]:
weights_named = torch.tensor([0.2126,0.7152,0.0722],names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [58]:
img_named = img_t.refine_names('channels','rows','columns')
img_named.names

('channels', 'rows', 'columns')

In [59]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]], names=('channels', 'rows', 'columns'))

In [60]:
a = torch.tensor(list(range(9)))

In [61]:
b = torch.tensor(a.view(3,3))

<ipython-input-61-0b4990de12ff>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  b = torch.tensor(a.view(3,3))


In [62]:
c = b[1:,1:]
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [63]:
c

tensor([[4, 5],
        [7, 8]])